[2024-07-25T14:30:42.748-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T14:30:42.753-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:15:00+00:00 [queued]>
[2024-07-25T14:30:42.757-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:15:00+00:00 [queued]>
[2024-07-25T14:30:42.757-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T14:30:42.770-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 14:15:00+00:00
[2024-07-25T14:30:42.772-0300] {standard_task_runner.py:64} INFO - Started process 2593546 to run task
[2024-07-25T14:30:42.774-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T14:15:00+00:00', '--job-id', '2109', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmplfmj7le3']
[2024-07-25T14:30:42.775-0300] {standard_task_runner.py:91} INFO - Job 2109: Subtask get_5m_info
[2024-07-25T14:30:42.805-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:15:00+00:00 [running]> on host Galaxybook.
[2024-07-25T14:30:42.856-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T14:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T14:15:00+00:00'
[2024-07-25T14:30:42.856-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T14:30:42.863-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T14:30:42.863-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 232, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/utils/context.py", line 266, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
ValueError: too many values to unpack (expected 2)
[2024-07-25T14:30:42.867-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T14:15:00+00:00, execution_date=20240725T141500, start_date=20240725T173042, end_date=20240725T173042
[2024-07-25T14:30:42.878-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2109 for task get_5m_info (too many values to unpack (expected 2); 2593546)
[2024-07-25T14:30:42.908-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T14:30:42.915-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T14:30:42.916-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T15:00:59.431-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T15:00:59.435-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:15:00+00:00 [queued]>
[2024-07-25T15:00:59.439-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:15:00+00:00 [queued]>
[2024-07-25T15:00:59.439-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T15:00:59.452-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 14:15:00+00:00
[2024-07-25T15:00:59.454-0300] {standard_task_runner.py:64} INFO - Started process 2620418 to run task
[2024-07-25T15:00:59.456-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mercado_5m', 'get_5m_info', 'scheduled__2024-07-25T14:15:00+00:00', '--job-id', '2483', '--raw', '--subdir', 'DAGS_FOLDER/mercado_dag.py', '--cfg-path', '/tmp/tmptjj0kid5']
[2024-07-25T15:00:59.457-0300] {standard_task_runner.py:91} INFO - Job 2483: Subtask get_5m_info
[2024-07-25T15:00:59.483-0300] {task_command.py:426} INFO - Running <TaskInstance: Mercado_5m.get_5m_info scheduled__2024-07-25T14:15:00+00:00 [running]> on host Galaxybook.
[2024-07-25T15:00:59.534-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Mercado_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T14:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T14:15:00+00:00'
[2024-07-25T15:00:59.535-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T15:00:59.598-0300] {base.py:84} INFO - Using connection ID 'mercado_default' for task execution.
[2024-07-25T15:00:59.599-0300] {mercado_hook.py:31} INFO - URL: https://api.mercadobitcoin.net/api/v4/candles?symbol=BTC-BRL&resolution=5m&to=1721928000&from=1721927700
[2024-07-25T15:00:59.871-0300] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T15:00:59.872-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T15:00:59.875-0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Mercado_5m, task_id=get_5m_info, run_id=scheduled__2024-07-25T14:15:00+00:00, execution_date=20240725T141500, start_date=20240725T180059, end_date=20240725T180059
[2024-07-25T15:00:59.918-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T15:00:59.925-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T15:00:59.925-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
