[2024-07-25T13:18:12.000-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T13:18:12.007-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Binance_5m.get_5m_info manual__2024-07-25T16:18:10.734018+00:00 [queued]>
[2024-07-25T13:18:12.011-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Binance_5m.get_5m_info manual__2024-07-25T16:18:10.734018+00:00 [queued]>
[2024-07-25T13:18:12.011-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T13:18:12.025-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_5m_info> on 2024-07-25 16:18:10.734018+00:00
[2024-07-25T13:18:12.027-0300] {standard_task_runner.py:64} INFO - Started process 2557072 to run task
[2024-07-25T13:18:12.030-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Binance_5m', 'get_5m_info', 'manual__2024-07-25T16:18:10.734018+00:00', '--job-id', '2087', '--raw', '--subdir', 'DAGS_FOLDER/binance_dag.py', '--cfg-path', '/tmp/tmp7n1piwwp']
[2024-07-25T13:18:12.031-0300] {standard_task_runner.py:91} INFO - Job 2087: Subtask get_5m_info
[2024-07-25T13:18:12.067-0300] {task_command.py:426} INFO - Running <TaskInstance: Binance_5m.get_5m_info manual__2024-07-25T16:18:10.734018+00:00 [running]> on host Galaxybook.
[2024-07-25T13:18:12.132-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Binance_5m' AIRFLOW_CTX_TASK_ID='get_5m_info' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T16:18:10.734018+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-25T16:18:10.734018+00:00'
[2024-07-25T13:18:12.132-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T13:18:12.142-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T13:18:12.142-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Documentos/data_pipeline_airflow/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugoviana/Projetos/crypto-etl/airflow_pipeline/dags/binance_dag.py", line 20, in execute
    ti.log.info(f"End time: {end_time}")
    ^^^^^^
AttributeError: 'str' object has no attribute 'log'
[2024-07-25T13:18:12.238-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Binance_5m, task_id=get_5m_info, run_id=manual__2024-07-25T16:18:10.734018+00:00, execution_date=20240725T161810, start_date=20240725T161812, end_date=20240725T161812
[2024-07-25T13:18:12.253-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 2087 for task get_5m_info ('str' object has no attribute 'log'; 2557072)
[2024-07-25T13:18:12.283-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T13:18:12.292-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T13:18:12.292-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
